apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  finalizers:
    - fleet.cattle.io/helmop-finalizer
##NAME
  name: lane2-app1
  namespace: fleet-default
spec:
  correctDrift: {}
  helm:
    releaseName: app1
    repo: oci://registry.192.168.8.170.sslip.io/my-charts/app1
    values:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: lane
                    operator: In
                    values:
                      - lane02
      replicaCount: 1
      service:
        type: ClusterIP
  #Release
    version: 0.2.0
  insecureSkipTLSVerify: true
  #NameSpace
  namespace: lane2
  targets:
    - clusterName: toppan-rhel-rke2
